#!/usr/bin/env python3
"""Lightweight CI wrapper that turns a PR into a prompt_guidance.review
call and posts the result as one Markdown PR comment. Re-runs on PR
update edit-in-place via the <!-- prompt-guidance:v1 --> marker.

Reads:  PR metadata via gh CLI.
Writes: exactly one PR comment per PR (created or edited in place).
        Nothing else. No file edits. No git push. No PR creation.

Always exit 0 when the comment is posted/updated. WARN/RECOMMEND in
the review output do NOT fail the workflow.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

# allow running both as `python -m scripts.review_pr` and standalone
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from prompt_guidance.review import review, GUIDANCE_VERSION  # noqa: E402

MARKER = "<!-- prompt-guidance:v1 -->"


def _gh(*args: str, input_text: str | None = None) -> str:
    return subprocess.check_output(
        ("gh", *args), text=True,
        input=input_text,
    ).strip()


def _pr_metadata(pr: str) -> dict:
    """PR header fields. Comments are fetched separately via the REST
    API in `_list_pr_comments_rest` because `gh pr view --json
    comments` returns GraphQL node IDs (strings) rather than the
    numeric REST IDs needed for PATCH-by-id."""
    raw = _gh("pr", "view", pr, "--json",
              "title,body,headRefName,number,files,baseRefName")
    return json.loads(raw)


def _list_pr_comments_rest(pr: str, repo: str) -> list[dict]:
    """List issue comments on a PR using the REST API.

    Returns a list of dicts with a numeric ``id`` (the issue-comment
    REST id). Used by `_existing_comment_id` so `PATCH
    /repos/{repo}/issues/comments/{id}` can target the correct
    comment. Robust to non-list / non-dict shapes (returns []).
    """
    try:
        raw = _gh("api", f"repos/{repo}/issues/{pr}/comments")
    except Exception:
        return []
    try:
        data = json.loads(raw)
    except Exception:
        return []
    return data if isinstance(data, list) else []


def _build_context(repo: str, meta: dict) -> dict:
    changed = [f["path"] for f in meta.get("files", []) if "path" in f]
    return {
        "source": "pr",
        "repo": repo,
        "branch": meta.get("headRefName"),
        "changed_paths": changed,
        "task_name": None,
        "task_class": None,
        "priority": None,
        "timeout_s": None,
        "side_effects": ["filesystem", "github"],
        "declared_impact": [],
    }


def _bullets(xs: list[str]) -> str:
    return "\n".join(f"- {x}" for x in xs) if xs else "_none_"


def _code_list(xs: list[str]) -> str:
    return ", ".join(f"`{x}`" for x in xs) if xs else "_none_"


def render_comment(out: dict, commit_sha_short: str) -> str:
    body = (
        f"{MARKER}\n"
        f"### Prompt Guidance Review\n\n"
        f"| Field | Value |\n"
        f"|---|---|\n"
        f"| Status | **{out['status']}** |\n"
        f"| Risk | **{out['risk']}** |\n"
        f"| Mirror required | **{str(out['mirror_required']).lower()}** |\n"
        f"| Detected intent | `{out['detected_intent']}` |\n"
        f"| Guidance version | `{out['guidance_version']}` |\n\n"
        f"**Detected impact:**\n{_bullets(out['impact_areas'])}\n\n"
        f"**Recommended mirror targets:**\n{_bullets(out['mirror_targets'])}\n\n"
        f"**Recommended repositories:**\n{_bullets(out['recommended_repositories'])}\n\n"
        f"**Suggested follow-up PR:**\n"
        f"> {out['suggested_pr_title'] or '_none_'}\n\n"
        f"**Scope:**\n{out['suggested_pr_scope'] or '_none_'}\n\n"
        f"**Git guidance:**\n{_bullets(out['git_guidance'])}\n\n"
        f"**Orchestration guidance:**\n{_bullets(out['orchestration_guidance'])}\n\n"
        f"**Missing fields:**\n{_code_list(out['missing_fields'])}\n\n"
        f"---\n"
        f"_This is advisory only. It does not block merge. "
        f"Generated by `JAPAM-AI/governance` via reusable workflow "
        f"`guidance-review.yml`._\n\n"
        f"_Source-of-truth function: `prompt_guidance.review` "
        f"(governance@{commit_sha_short})._\n"
    )
    return body


def _existing_comment_id(pr: str, repo: str) -> int | None:
    """Return the numeric REST id of the bot's existing comment, or None.

    Walks REST issue comments (via `_list_pr_comments_rest`) and finds
    the FIRST comment whose body starts with the MARKER. Returns the
    integer ``id`` directly. Robust to malformed responses: missing
    or non-int ids fall through to None so the caller takes the
    create-new path rather than crashing.
    """
    for c in _list_pr_comments_rest(pr, repo):
        if not isinstance(c, dict):
            continue
        if not c.get("body", "").startswith(MARKER):
            continue
        cid = c.get("id")
        if isinstance(cid, int):
            return cid
        return None
    return None


def _upsert_comment(pr: str, body: str, repo: str) -> None:
    """Create-or-edit the single bot comment on a PR.

    Looks up the existing bot comment via REST (`_existing_comment_id`).
    If found, PATCHes that exact REST id. If not, creates a new comment
    via `gh pr comment`. The bot manages exactly one comment per PR
    identified by the leading <!-- prompt-guidance:v1 --> marker.
    """
    comment_id = _existing_comment_id(pr, repo)
    if comment_id is None:
        subprocess.run(
            ("gh", "pr", "comment", pr, "--body-file", "-"),
            input=body, text=True, check=True,
        )
        return
    subprocess.run(
        (
            "gh", "api",
            f"repos/{repo}/issues/comments/{comment_id}",
            "--method", "PATCH",
            "-F", "body=@-",
        ),
        input=body, text=True, check=True,
    )


def main() -> int:
    """Entry point for the GitHub Actions reusable workflow.

    Always returns 0. This wrapper is advisory; a non-zero exit would
    fail the calling workflow step, which would tempt operators to
    treat the comment as a merge gate. Any exception (gh CLI failure,
    JSON parse failure, GitHub auth failure, comment upsert failure)
    is caught here, logged to stderr for diagnostics, and the wrapper
    still exits 0.
    """
    try:
        repo = os.environ.get("GITHUB_REPOSITORY", "")
        pr = os.environ.get("GITHUB_PR_NUMBER", "")
        commit_sha_short = (os.environ.get("GITHUB_SHA") or "unknown")[:7]
        if not repo or not pr:
            print("review_pr: GITHUB_REPOSITORY and GITHUB_PR_NUMBER required",
                  file=sys.stderr)
            return 0
        meta = _pr_metadata(pr)
        prompt = ((meta.get("title") or "") + "\n\n" + (meta.get("body") or "")).strip()
        ctx = _build_context(repo, meta)
        out = review(prompt, ctx)
        body = render_comment(out, commit_sha_short)
        _upsert_comment(pr, body, repo)
        return 0
    except Exception as exc:
        print(f"review_pr: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 0


if __name__ == "__main__":
    sys.exit(main())
